---
title: "judgment day"
output: pdf_document
---

```{r}
library(reticulate)
library(data.table)
library(tidyverse)
library(pROC)
use_virtualenv("../venv/", required = TRUE)
source_python("util.py")
source_python("models.py")
```

# Functions

```{r}
calculate_yhat_sklearn <- function(model, x) {
  return(model$predict_proba(x)[,2])
}

calculate_yhat_NN <- function(model, x) {
  return(model$predict(x))
}

calculate_TPR <- function(y, yhat) {
  P <- sum(y == 1)
  TP <- sum(((yhat > 0.5) == 1) & (y == 1))
  TPR <- TP / P
  return(TPR)
}

calculate_FPR <- function(y, yhat) {
  N <- sum(y == 0)
  FP <- sum(((yhat > 0.5) == 1) & (y == 0))
  FPR <- FP / N
  return(FPR)
}

calculate_AUC <- function(y, yhat) {
  df <- data.frame(a=y, p=yhat)
  df <- df[order(df$a),]
  roc_obj <- roc(df$a, df$p)
  AUC <- auc(roc_obj)
  TPR10 <- coords(roc_obj, x=0.9, input="specificity")$sensitivity  # Sensitivity is AKA the FPR
  return(c(AUC=AUC, TPR10=TPR10))
}

calculate_Positivity <- function(yhat) {
  yhat_binary <- (yhat > 0.5)
  positivity <- mean(yhat_binary)
  return(positivity)
}

# This function assumes that the data variables are already defined in the environment.
# E.g. Black_x, AsianPI_y, etc.
calculate_results <- function(model, model_yhat_fn) {
  # (1) Prepare results matrix
  race_eth_all <- c('White', 'Black', 'AsianPI', 'AmeriIndian')
  results <- matrix(nrow = length(race_eth_all), ncol = 6)
  rownames(results) <- race_eth_all
  colnames(results) <- c('TPR', 'FPR',  'AUC', 'TPR10', 'Accuracy', 'Positivity')
  
  # (2) Calculate TPR, AUC, and TPR10 for each race/ethnicity
  for (i in 1:length(race_eth_all)) {
    race_eth <- race_eth_all[i]
    x <- get(paste0(race_eth, '_x'))  # get() gets a variable in the environment by name
    y <- get(paste0(race_eth, '_y'))
    yhat <- model_yhat_fn(model, x)  # Note this depends on function arguments
    
    results[i, 1] <- calculate_TPR(y, yhat)
    results[i, 2] <- calculate_FPR(y, yhat)
    results[i, c(3, 4)] <- calculate_AUC(y, yhat)
    results[i, 5] <- mean((yhat > 0.5) == y)
    results[i, 6] <- calculate_Positivity(yhat)
  }
  
  return(data.frame(results))
}
```

```{r}
read_race_data <- function(file, outome, unaware=FALSE) {
  x <<- fread(file)
  x$outcome <- as.numeric(x$outcome == outcome)
  
  AmeriIndian_x <<- x %>% filter(race_AmeriIndian == 1)
  AmeriIndian_y <<- AmeriIndian_x$outcome
  AmeriIndian_x <<- AmeriIndian_x %>% select(-outcome)
  if (unaware)
    AmeriIndian_x <<- AmeriIndian_x %>% select(-race_AmeriIndian, -race_AsianPI, -race_Black, -race_White)
  
  AsianPI_x <<- x %>% filter(race_AsianPI == 1)
  AsianPI_y <<- AsianPI_x$outcome
  AsianPI_x <<- AsianPI_x %>% select(-outcome)
  if (unaware)
    AsianPI_x <<- AsianPI_x %>% select(-race_AmeriIndian, -race_AsianPI, -race_Black, -race_White)
  
  Black_x <<- x %>% filter(race_Black == 1)
  Black_y <<- Black_x$outcome
  Black_x <<- Black_x %>% select(-outcome)
  if (unaware)
    Black_x <<- Black_x %>% select(-race_AmeriIndian, -race_AsianPI, -race_Black, -race_White)
  
  White_x <<- x %>% filter(race_White == 1)
  White_y <<- White_x$outcome
  White_x <<- White_x %>% select(-outcome)
  if (unaware)
    White_x <<- White_x %>% select(-race_AmeriIndian, -race_AsianPI, -race_Black, -race_White)
}
```

# Fairness evaluations

## Early Stillbirth

```{r}
file <- '../data/final/stillbirth_test.csv'
outcome <- 'early stillbirth'
```

```{r}
## RACE-AWARE Columns
read_race_data(file, outcome, unaware = FALSE)

# Logistic Regression
lr_early_aware <- load_pickle("../models/lr_early_aware")
lr_early_aware_r <- calculate_results(model = lr_early_aware, model_yhat_fn = calculate_yhat_sklearn)
lr_early_aware_r

# LightGBM
gb_early_aware <- load_pickle("../models/gb_early_aware")
gb_early_aware_r <- calculate_results(model = gb_early_aware, model_yhat_fn = calculate_yhat_sklearn)
gb_early_aware_r

# ReLU Network
relu_early_aware <- load_NN("../models/lrelu_early_aware")
relu_early_aware_r <- calculate_results(relu_early_aware, calculate_yhat_NN)
relu_early_aware_r

## SELU Network
selu_early_aware <- load_NN("../models/selu_early_aware")
selu_early_aware_r <- calculate_results(selu_early_aware, calculate_yhat_NN)
selu_early_aware_r
```

```{r}
## RACE-UNAWARE Columns
read_race_data(file, outcome, unaware = TRUE)

# Logistic Regression
lr_early_unaware <- load_pickle("../models/lr_early_unaware")
lr_early_unaware_r <- calculate_results(model = lr_early_unaware, model_yhat_fn = calculate_yhat_sklearn)
lr_early_unaware_r

# LightGBM
gb_early_unaware <- load_pickle("../models/gb_early_unaware")
gb_early_unaware_r <- calculate_results(model = gb_early_unaware, model_yhat_fn = calculate_yhat_sklearn)
gb_early_unaware_r

# ReLU Network
relu_early_unaware <- load_NN("../models/lrelu_early_unaware")
relu_early_unaware_r <- calculate_results(relu_early_unaware, calculate_yhat_NN)
relu_early_unaware_r

## SELU Network
selu_early_unaware <- load_NN("../models/selu_early_unaware")
selu_early_unaware_r <- calculate_results(selu_early_unaware, calculate_yhat_NN)
selu_early_unaware_r
```

## Late Stillbirth

```{r}
file <- '../data/final/stillbirth_test.csv'
outcome <- 'late stillbirth'
```

```{r}
## RACE-AWARE Columns
read_race_data(file, outcome, unaware = FALSE)

# Logistic Regression
lr_late_aware <- load_pickle("../models/lr_late_aware")
lr_late_aware_r <- calculate_results(model = lr_late_aware, model_yhat_fn = calculate_yhat_sklearn)
lr_late_aware_r

# LightGBM
gb_late_aware <- load_pickle("../models/gb_late_aware")
gb_late_aware_r <- calculate_results(model = gb_late_aware, model_yhat_fn = calculate_yhat_sklearn)
gb_late_aware_r

# ReLU Network
relu_late_aware <- load_NN("../models/lrelu_late_aware")
relu_late_aware_r <- calculate_results(relu_late_aware, calculate_yhat_NN)
relu_late_aware_r

## SELU Network
selu_late_aware <- load_NN("../models/selu_late_aware")
selu_late_aware_r <- calculate_results(selu_late_aware, calculate_yhat_NN)
selu_late_aware_r
```

```{r}
## RACE-UNAWARE Columns
read_race_data(file, outcome, unaware = TRUE)

# Logistic Regression
lr_late_unaware <- load_pickle("../models/lr_late_unaware")
lr_late_unaware_r <- calculate_results(model = lr_late_unaware, model_yhat_fn = calculate_yhat_sklearn)
lr_late_unaware_r

# LightGBM
gb_late_unaware <- load_pickle("../models/gb_late_unaware")
gb_late_unaware_r <- calculate_results(model = gb_late_unaware, model_yhat_fn = calculate_yhat_sklearn)
gb_late_unaware_r

# ReLU Network
relu_late_unaware <- load_NN("../models/lrelu_late_unaware")
relu_late_unaware_r <- calculate_results(relu_late_unaware, calculate_yhat_NN)
relu_late_unaware_r

## SELU Network
selu_late_unaware <- load_NN("../models/selu_late_unaware")
selu_late_unaware_r <- calculate_results(selu_late_unaware, calculate_yhat_NN)
selu_late_unaware_r
```

## Preterm Birth

```{r}
file <- '../data/final/preterm_test.csv'
outcome <- 'preterm'
```


```{r}
## RACE-AWARE Columns
read_race_data(file, outcome, unaware = FALSE)

# Logistic Regression
lr_preterm_aware <- load_pickle("../models/lr_preterm_aware")
lr_preterm_aware_r <- calculate_results(model = lr_preterm_aware, model_yhat_fn = calculate_yhat_sklearn)
lr_preterm_aware_r

# LightGBM
gb_preterm_aware <- load_pickle("../models/gb_preterm_aware")
gb_preterm_aware_r <- calculate_results(model = gb_preterm_aware, model_yhat_fn = calculate_yhat_sklearn)
gb_preterm_aware_r

# ReLU Network
relu_preterm_aware <- load_NN("../models/lrelu_preterm_aware")
relu_preterm_aware_r <- calculate_results(relu_preterm_aware, calculate_yhat_NN)
relu_preterm_aware_r

## SELU Network
selu_preterm_aware <- load_NN("../models/selu_preterm_aware")
selu_preterm_aware_r <- calculate_results(selu_preterm_aware, calculate_yhat_NN)
selu_preterm_aware_r
```

```{r}
## RACE-UNAWARE Columns
read_race_data(file, outcome, unaware = TRUE)

# Logistic Regression
lr_preterm_unaware <- load_pickle("../models/lr_preterm_unaware")
lr_preterm_unaware_r <- calculate_results(model = lr_preterm_unaware, model_yhat_fn = calculate_yhat_sklearn)
lr_preterm_unaware_r

# LightGBM
gb_preterm_unaware <- load_pickle("../models/gb_preterm_unaware")
gb_preterm_unaware_r <- calculate_results(model = gb_preterm_unaware, model_yhat_fn = calculate_yhat_sklearn)
gb_preterm_unaware_r

# ReLU Network
relu_preterm_unaware <- load_NN("../models/lrelu_preterm_unaware")
relu_preterm_unaware_r <- calculate_results(relu_preterm_unaware, calculate_yhat_NN)
relu_preterm_unaware_r

## SELU Network
selu_preterm_unaware <- load_NN("../models/selu_preterm_unaware")
selu_preterm_unaware_r <- calculate_results(selu_preterm_unaware, calculate_yhat_NN)
selu_preterm_unaware_r
```

# Save results

```{r}
# AWARE RESULTS
lr_early_aware_r$model <- 'lr'
lr_early_aware_r$task <- 'early'
lr_early_aware_r$raceeth <- rownames(lr_early_aware_r)
lr_early_aware_r$aware <- TRUE
gb_early_aware_r$model <- 'gb'
gb_early_aware_r$task <- 'early'
gb_early_aware_r$raceeth <- rownames(gb_early_aware_r)
gb_early_aware_r$aware <- TRUE
relu_early_aware_r$model <- 'lrelu'
relu_early_aware_r$task <- 'early'
relu_early_aware_r$raceeth <- rownames(relu_early_aware_r)
relu_early_aware_r$aware <- TRUE
selu_early_aware_r$model <- 'selu'
selu_early_aware_r$task <- 'early'
selu_early_aware_r$raceeth <- rownames(selu_early_aware_r)
selu_early_aware_r$aware <- TRUE

lr_late_aware_r$model <- 'lr'
lr_late_aware_r$task <- 'late'
lr_late_aware_r$raceeth <- rownames(lr_late_aware_r)
lr_late_aware_r$aware <- TRUE
gb_late_aware_r$model <- 'gb'
gb_late_aware_r$task <- 'late'
gb_late_aware_r$raceeth <- rownames(gb_late_aware_r)
gb_late_aware_r$aware <- TRUE
relu_late_aware_r$model <- 'lrelu'
relu_late_aware_r$task <- 'late'
relu_late_aware_r$raceeth <- rownames(relu_late_aware_r)
relu_late_aware_r$aware <- TRUE
selu_late_aware_r$model <- 'selu'
selu_late_aware_r$task <- 'late'
selu_late_aware_r$raceeth <- rownames(selu_late_aware_r)
selu_late_aware_r$aware <- TRUE

lr_preterm_aware_r$model <- 'lr'
lr_preterm_aware_r$task <- 'preterm'
lr_preterm_aware_r$raceeth <- rownames(lr_preterm_aware_r)
lr_preterm_aware_r$aware <- TRUE
gb_preterm_aware_r$model <- 'gb'
gb_preterm_aware_r$task <- 'preterm'
gb_preterm_aware_r$raceeth <- rownames(gb_preterm_aware_r)
gb_preterm_aware_r$aware <- TRUE
relu_preterm_aware_r$model <- 'lrelu'
relu_preterm_aware_r$task <- 'preterm'
relu_preterm_aware_r$raceeth <- rownames(relu_preterm_aware_r)
relu_preterm_aware_r$aware <- TRUE
selu_preterm_aware_r$model <- 'selu'
selu_preterm_aware_r$task <- 'preterm'
selu_preterm_aware_r$raceeth <- rownames(selu_preterm_aware_r)
selu_preterm_aware_r$aware <- TRUE
```

```{r}
# UNAWARE RESULTS
lr_early_unaware_r$model <- 'lr'
lr_early_unaware_r$task <- 'early'
lr_early_unaware_r$raceeth <- rownames(lr_early_unaware_r)
lr_early_unaware_r$aware <- FALSE
gb_early_unaware_r$model <- 'gb'
gb_early_unaware_r$task <- 'early'
gb_early_unaware_r$raceeth <- rownames(gb_early_unaware_r)
gb_early_unaware_r$aware <- FALSE
relu_early_unaware_r$model <- 'lrelu'
relu_early_unaware_r$task <- 'early'
relu_early_unaware_r$raceeth <- rownames(relu_early_unaware_r)
relu_early_unaware_r$aware <- FALSE
selu_early_unaware_r$model <- 'selu'
selu_early_unaware_r$task <- 'early'
selu_early_unaware_r$raceeth <- rownames(selu_early_unaware_r)
selu_early_unaware_r$aware <- FALSE

lr_late_unaware_r$model <- 'lr'
lr_late_unaware_r$task <- 'late'
lr_late_unaware_r$raceeth <- rownames(lr_late_unaware_r)
lr_late_unaware_r$aware <- FALSE
gb_late_unaware_r$model <- 'gb'
gb_late_unaware_r$task <- 'late'
gb_late_unaware_r$raceeth <- rownames(gb_late_unaware_r)
gb_late_unaware_r$aware <- FALSE
relu_late_unaware_r$model <- 'lrelu'
relu_late_unaware_r$task <- 'late'
relu_late_unaware_r$raceeth <- rownames(relu_late_unaware_r)
relu_late_unaware_r$aware <- FALSE
selu_late_unaware_r$model <- 'selu'
selu_late_unaware_r$task <- 'late'
selu_late_unaware_r$raceeth <- rownames(selu_late_unaware_r)
selu_late_unaware_r$aware <- FALSE

lr_preterm_unaware_r$model <- 'lr'
lr_preterm_unaware_r$task <- 'preterm'
lr_preterm_unaware_r$raceeth <- rownames(lr_preterm_unaware_r)
lr_preterm_unaware_r$aware <- FALSE
gb_preterm_unaware_r$model <- 'gb'
gb_preterm_unaware_r$task <- 'preterm'
gb_preterm_unaware_r$raceeth <- rownames(gb_preterm_unaware_r)
gb_preterm_unaware_r$aware <- FALSE
relu_preterm_unaware_r$model <- 'lrelu'
relu_preterm_unaware_r$task <- 'preterm'
relu_preterm_unaware_r$raceeth <- rownames(relu_preterm_unaware_r)
relu_preterm_unaware_r$aware <- FALSE
selu_preterm_unaware_r$model <- 'selu'
selu_preterm_unaware_r$task <- 'preterm'
selu_preterm_unaware_r$raceeth <- rownames(selu_preterm_unaware_r)
selu_preterm_unaware_r$aware <- FALSE
```

```{r}
results_varnames <- ls(pattern = '.+_r$')
results_combined <- mget(results_varnames) %>%
  bind_rows(.id = 'varname') %>%
  remove_rownames()
results_combined
```

```{r}
fwrite(results_combined, '../data/results.csv')
```