---
title: "ingest_clean"
author: "bradley"
date: "3/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
```

```{r}
y <- read.fwf("../data/cdc/fatality_2015.txt", 
              widths = c(6, 1, 2, 1, 4, 2, 4, 4, 1, 2, 2, 3, 1, 1, 1, 16, 1, 31, 1, 1, 2, 2, 1, 2, 4, 1, 4, 2, 3, 5, 1, 17, 1, 1, 2, 1, 2, 1, 1, 3, 1, 1, 1, 1, 26, 1, 4, 2, 2, 2, 2, 2, 1, 9, 3, 2, 2, 1, 24, 1, 2, 2, 2, 2, 1, 4, 2, 4, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 17, 1, 1, 1, 2, 1, 9, 1, 1, 2, 2, 4, 3, 1, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 4, 4, 2, 1, 1, 1, 1, 1, 11, 66, 2610),
              header = FALSE,
              n = 100,
              stringsAsFactors = FALSE,
              col.names = c("F",
                            "Version",
                            "FILLER",
                            "Obstetric Estimate Tabulation Flag",
                            "Delivery Year",
                            "Delivery Month",
                            "F",
                            "Delivery Time",
                            "Weekday",
                            "Territory of Occurence",
                            "F",
                            "County FIPS",
                            "County Population",
                            "Delivery Place (revised)",
                            "Delivery Place",
                            "F",
                            "Delivery Place Recode",
                            "F",
                            "Mother's Age Imputed",
                            "Reported age of Mother Flag",
                            "Mother's single year of age",
                            "Mother's age recode 14",
                            "Mother's age recode 9",
                            "Mother's Birth Country",
                            "F",
                            "Mother's Birth State REcode",
                            "Mother's FIPS County",
                            "F",
                            "Population of Residence County",
                            "F",
                            "Record Type",
                            "Residence Status",
                            "Mother's Race Recode 31",
                            "Mother's Race Recode 6",
                            "Mother's Race Recode 15",
                            "Mother's BRidged Race Recode",
                            "Mother's Race Imputed",
                            "F",
                            "Mother's Hispanic Origin",
                            "Mother's Bridged Race/Hispanic Origin",
                            "Mother's Race/Hispanic Origin",
                            "Mother's Education Revised",
                            "F",
                            "Father's Reported Age Used",
                            "F",
                            "Father's Combined Age",
                            "Father's Age Recode 11",
                            "Prior BIrths Now Living",
                            "Prior Births Now Dead",
                            "F",
                            "Live Birth Order Recode",
                            "F",
                            "Interval Since Last Live Birhtday Recode",
                            "Interval Since Last Live Birth Recode 11",
                            "Month Prenatal Care Began (Revised)",
                            "Month PRenatal Care Began (Revised) A",
                            "F",
                            "WIC",
                            "Cigarettes Before Pregnancy",
                            "Cigarettes 1st Trimester",
                            "Cigarettes 2nd Trimester",
                            "Cigarettes 3rd Trimester",
                            "Cigarette Recode (revised)",
                            "F",
                            "Mother's Height (Inch)",
                            "BMI",
                            "BMI Recode",
                            "F",
                            "Prepregnancy Weight Recode",
                            "F",
                            "Prepregnancy Diabetes",
                            "Gestational Diabetes",
                            "Prepregnancy Hpertension",
                            "Gestational Hypertension",
                            "Hypertension Eclampsia",
                            "Infertility Treatment",
                            "Fertility Enhancing Drugs",
                            "Asst Reproductive Technology",
                            "Previous Cesareans",
                            "Previous Cesareans Num",
                            "F",
                            "DIabetes",
                            "Chronic Hypertension",
                            "Pregnancy ASsociated Hypertension",
                            "Eclampsia",
                            "Breech Delivery",
                            "Fetal PResentation",
                            "Route and Method of Delivery",
                            "Trial of Labour Attempted",
                            "Delviery Method Recode (revised)",
                            "Forceps",
                            "Vacuum",
                            "Delivery Method Recode",
                            "Ruptured Uterus",
                            "Admit to Intensive Care",
                            "Attendant",
                            "F",
                            "Plurality Recode",
                            "F",
                            "Plurality Imputed",
                            "F",
                            "Set Order Recode",
                            "F",
                            "Sex of Infant",
                            "Sex Imputed",
                            "Last Normal Menses Month",
                            "F",
                            "Last Normal Menses Year",
                            "F",
                            "Gestation Imputed Flag",
                            "Obstetric Estimate of Gestation Using Flag",
                            "Gestation Detail in Weeks",
                            "Gestation Recode 12",
                            "Gestation Recode 5",
                            "Obstetric Gestation",
                            "F",
                            "Combined Gestation Used Flag",
                            "F",
                            "COmbined Gestation Used Flag",
                            "Obstetric Estimate Edited",
                            "Obstetric Estimate Recode 12",
                            "Obstetric Estimate Recode 5",
                            "F",
                            "Birth Weight Grams",
                            "Birth Weight Recode",
                            "Birth Weight Recode 4",
                            "F",
                            "Estimated Time of Fetal Death",
                            "Autopsy Performed",
                            "Histological Placental Exam Performed",
                            "Autopsy/Hist Results used in Cause",
                            "F",
                            "Flags",
                            "F"
                            ))

end_flags <- c("Education of Mother",
                            "Obstetric Estimate of Gestation",
                            "Tobaccu Use",
                            "Mother's Height",
                            "Pregnancy Weight",
                            "WIC",
                            "Prepregnancy diabetes",
                            "Gestational diabetes",
                            "prepregnancy hypertension",
                            "gestational hypertension",
                            "hypertension eclampsia",
                            "infertility treatment",
                            "fertility enhance drug",
                            "reproductive tech",
                            "prev cesarean",
                            "num of prev cesarean",
                            "fetal presentation",
                            "final route and method of delivery",
                            "trial of labour attempted",
                            "ruptured uterus",
                            "admission to ICU",
                            "month prenatal care began",
                            "combined gestation",
                            "cig before preg",
                            "cig before 1",
                            "cig before 2",
                            "cig before 3",
                            "facility",
                            "delivery method recode",
                            "diabetes flag",
                            "chron hyper flag",
                            "preg assoc hyper flag",
                            "eclampsia flag",
                            "breech flag",
                            "forceps flag",
                            "vacuum flag",
                            "mother's hispanic origin flag",
                            "mother's race revised flag",
                            "father's age flag",
                            "live birth month flag",
                            "F",
                            "last normal menses month flag",
                            "F",
                            "last normal menses year flag",
                            "mother's age flag",
                            "attendant flag",
                            "F",
                            "estimated time of fetal death (revised)",
                            "autopsy flag",
                            "histological placement flag",
                            "mothers bridged race recode flag",
                            "num of prev births flag")
```